<?php

namespace AppBundle\Repository;

use AppBundle\Interfaces\Repository\IngredientRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository implements IngredientRepositoryInterface
{
    public function save ($entity) {
        $this->_em->persist($entity);
        $this->_em->flush();
    }
}
