<?php

namespace AppBundle\Repository;

use AppBundle\Interfaces\Repository\PizzaRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * PizzaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaRepository extends EntityRepository implements PizzaRepositoryInterface
{
    public function save ($entity) {
        $this->_em->persist($entity);
        $this->_em->flush();
    }
}
