AppBundle\Entity\Ingredient:
    type: entity
    table: ingredients
    repositoryClass: AppBundle\Repository\IngredientRepository
    uniqueConstraints:
        ingredients_id_pk:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        cost:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
